export const appliances_header = ["SMALL APPLIANCES", "LARGE APPLIANCES"];

export const appliances_content: string[] = [
  "Blenders",
  "Deep Fryers",
  "Juicers",
  "Air Fryers",
  "Rice Cookers",
  "Toasters & Ovens",
  "Microwaves",
  "Bundles",
  "Vacuum Cleaners",
  "Kettles",
  "Yam Pounders",
  "Irons",
  "Washing Machines",
  "Fridges",
  "Freezers",
  "Air Conditioners",
  "Heaters",
  "Fans",
  "Air Purifiers",
  "Water Dispensers",
  "Generators & Inverters",
];
