export const Computing_header: string[] = [
  "COMPUTERS",
  "DATA STORAGE",
  " PRINTERS",
  "COMPUTER ACCESSORIES",
  " TOP BRANDS",
  "",
];

export const Computing_contents = [
  " Laptops",
  " Desktops",
  "External Hard Drives",
  "USB Flash Drives",
  " External Solid State",
  "Inkjet Printers",
  "Laser Printers",
  "Printer Ink & Toner",
  "Keyboards & Mice",
  "Uninterrupted Power Supply",
  " Memory Cards",
  " Batteries",
  " Scanners",
  "Video Projectors",
  "HP",
  " Lenovo",
  " Apple",
  "ASUS",
  " Huawei",
  " Microsoft",
  " Kingston",
  "Seagate",
  "",
  " Samsung",
  " Sandisk",
  " Toshiba",
];
