export const health_beauty_header: string[] = [
  "MAKE UP",
  "PERSONAL CARE",
  "FRAGRANCES",
  "HAIR CARE",
  "ORAL CARE",
  "HEALTH CARE",
  "VITAMINS & DIETARY SUPPLEMENTS",
  "",
  "",
];

export const health_beauty_contents: string[] = [
  "Concealers & Color Correctors",
  "Foundation",
  "Powder",
  "Lipstick",
  "Eyeliner & Kajal",
  "Mascara",
  "Skin Care",
  "Bath & Bathing Accessories",
  "Sunscreens & Tanning Products",
  "Contraceptives & Lubricants",
  "Piercing & Tattoo Supplies",
  "Deodorants & Antiperspirants",
  "Lip Care",
  "Women's",
  "Men's ",
  "Hair Accessories",
  "Hair Cutting Tools",
  "Shampoo & Conditioner",
  "Wigs & Accessories",
  "Teeth Whitening",
  "Toothbrushes",
  "Toothpaste",
  "First Aid",
  "Medical Supplies & Equipment",
  "Alternative Medicine",
  "Feminine Care",
  "Diabetes Care",
  "Herbal Supplements",
  "Vitamins & Minerals",
  "Supplements",
  "Multi & Prenatal Vitamins",
];
