export const phone_header: string[] = [
  "MOBILE PHONES",
  "TABLETS",
  "MOBILE ACCESSORIES",
  "TOP SMARTPHONES",
  "TOP PHONE BRANDS",
];
export const phone_content: string[] = [
  "Smartphones",
  "Basic Phones",
  "Refurbished Phones",
  "iPads",
  "Android Tablets",
  "Educational Tablets",
  "Tablet Accessories",
  "Accessory Kits",
  "Adapters",
  "Batteries",
  "Battery Chargers",
  "Bluetooth Headsets",
  "Cables",
  "Car Accessories",
  "Chargers",
  "Earphones & Headsets",
  "MicroSD Cards",
  "Screen Protectors",
  "Selfie Sticks & Tripods",
  "Smart Watches",
  "iPhone 11 Pro Max",
  "Samsung Galaxy S10",
  "iPhone 11",
  "Nokia 7.2",
  "Huawei Y9 S",
  "iPhone XS Max",
  "Infinix S5",
  "Samsung",
  "Apple",
  "Huawei",
  "Nokia",
  "Xiaomi",
  "Tecno",
];
